import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import LoginBtn from "./loginbtn";
import { getServerSession } from "next-auth";
import { authOptions } from "../../pages/api/auth/[...nextauth]";
import LoginOut from "./loginout";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  let session = await getServerSession(authOptions);
  return (
    <html lang="en">
      <body>
    <div className="navbar"> 
      <Link href="/" className="logo">Appleforum</Link> 
      <Link href="/list">List</Link> 
      
      {
      
        session  ? 
            <div>{session.user.name} 님 환영합니다.
            <LoginOut /> 
            </div> 
          : 
            <LoginBtn />
      }
    </div>  
         {children}
      </body>
    </html>
  );
}
